"""add_old_price_to_offers

Revision ID: 9abfd19b8eec
Revises: 42b51bfaa3e8
Create Date: 2025-12-03 17:06:33.903884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abfd19b8eec'
down_revision = '42b51bfaa3e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_price', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_column('old_price')

    # ### end Alembic commands ###
