"""Add foreign keys to offers table

Revision ID: d0c57dbdf586
Revises: 70a048e34438
Create Date: 2025-12-03 10:46:39.976110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c57dbdf586'
down_revision = '70a048e34438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('manufacturer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_offers_category_id_categories', 'categories', ['category_id'], ['id'])
        batch_op.create_foreign_key('fk_offers_seller_id_sellers', 'sellers', ['seller_id'], ['id'])
        batch_op.create_foreign_key('fk_offers_manufacturer_id_manufacturers', 'manufacturers', ['manufacturer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_offers_manufacturer_id_manufacturers', type_='foreignkey')
        batch_op.drop_constraint('fk_offers_seller_id_sellers', type_='foreignkey')
        batch_op.drop_constraint('fk_offers_category_id_categories', type_='foreignkey')
        batch_op.drop_column('manufacturer_id')
        batch_op.drop_column('category_id')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###
