"""add_social_network_configs_table

Revision ID: f8c2a9b4e5d7
Revises: 2b371f77cdd1
Create Date: 2025-12-03 19:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8c2a9b4e5d7'
down_revision = '2b371f77cdd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_network_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network', sa.String(length=50), nullable=False),
    sa.Column('prefix_text', sa.Text(), nullable=True),
    sa.Column('suffix_text', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_network_configs')
    # ### end Alembic commands ###

